/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package test.es.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Electronics service. Represents a row in the &quot;ES_Electronics&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>test.es.data.model.impl.ElectronicsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>test.es.data.model.impl.ElectronicsImpl</code>.
 * </p>
 *
 * @author Andrey Pletenev
 * @see Electronics
 * @generated
 */
@ProviderType
public interface ElectronicsModel
	extends BaseModel<Electronics>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a electronics model instance should use the {@link Electronics} interface instead.
	 */

	/**
	 * Returns the primary key of this electronics.
	 *
	 * @return the primary key of this electronics
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this electronics.
	 *
	 * @param primaryKey the primary key of this electronics
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this electronics.
	 *
	 * @return the mvcc version of this electronics
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this electronics.
	 *
	 * @param mvccVersion the mvcc version of this electronics
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this electronics.
	 *
	 * @return the uuid of this electronics
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this electronics.
	 *
	 * @param uuid the uuid of this electronics
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the electronics ID of this electronics.
	 *
	 * @return the electronics ID of this electronics
	 */
	public long getElectronicsId();

	/**
	 * Sets the electronics ID of this electronics.
	 *
	 * @param electronicsId the electronics ID of this electronics
	 */
	public void setElectronicsId(long electronicsId);

	/**
	 * Returns the group ID of this electronics.
	 *
	 * @return the group ID of this electronics
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this electronics.
	 *
	 * @param groupId the group ID of this electronics
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this electronics.
	 *
	 * @return the company ID of this electronics
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this electronics.
	 *
	 * @param companyId the company ID of this electronics
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this electronics.
	 *
	 * @return the user ID of this electronics
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this electronics.
	 *
	 * @param userId the user ID of this electronics
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this electronics.
	 *
	 * @return the user uuid of this electronics
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this electronics.
	 *
	 * @param userUuid the user uuid of this electronics
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this electronics.
	 *
	 * @return the user name of this electronics
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this electronics.
	 *
	 * @param userName the user name of this electronics
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this electronics.
	 *
	 * @return the create date of this electronics
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this electronics.
	 *
	 * @param createDate the create date of this electronics
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this electronics.
	 *
	 * @return the modified date of this electronics
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this electronics.
	 *
	 * @param modifiedDate the modified date of this electronics
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the electronics name of this electronics.
	 *
	 * @return the electronics name of this electronics
	 */
	@AutoEscape
	public String getElectronicsName();

	/**
	 * Sets the electronics name of this electronics.
	 *
	 * @param electronicsName the electronics name of this electronics
	 */
	public void setElectronicsName(String electronicsName);

	/**
	 * Returns the electro type ID of this electronics.
	 *
	 * @return the electro type ID of this electronics
	 */
	public long getElectroTypeId();

	/**
	 * Sets the electro type ID of this electronics.
	 *
	 * @param electroTypeId the electro type ID of this electronics
	 */
	public void setElectroTypeId(long electroTypeId);

	/**
	 * Returns the electronics price of this electronics.
	 *
	 * @return the electronics price of this electronics
	 */
	public long getElectronicsPrice();

	/**
	 * Sets the electronics price of this electronics.
	 *
	 * @param electronicsPrice the electronics price of this electronics
	 */
	public void setElectronicsPrice(long electronicsPrice);

	/**
	 * Returns the electronics count of this electronics.
	 *
	 * @return the electronics count of this electronics
	 */
	public int getElectronicsCount();

	/**
	 * Sets the electronics count of this electronics.
	 *
	 * @param electronicsCount the electronics count of this electronics
	 */
	public void setElectronicsCount(int electronicsCount);

	/**
	 * Returns the electronics in stock of this electronics.
	 *
	 * @return the electronics in stock of this electronics
	 */
	public Boolean getElectronicsInStock();

	/**
	 * Sets the electronics in stock of this electronics.
	 *
	 * @param electronicsInStock the electronics in stock of this electronics
	 */
	public void setElectronicsInStock(Boolean electronicsInStock);

	/**
	 * Returns the electronics archive of this electronics.
	 *
	 * @return the electronics archive of this electronics
	 */
	public boolean getElectronicsArchive();

	/**
	 * Returns <code>true</code> if this electronics is electronics archive.
	 *
	 * @return <code>true</code> if this electronics is electronics archive; <code>false</code> otherwise
	 */
	public boolean isElectronicsArchive();

	/**
	 * Sets whether this electronics is electronics archive.
	 *
	 * @param electronicsArchive the electronics archive of this electronics
	 */
	public void setElectronicsArchive(boolean electronicsArchive);

	/**
	 * Returns the electronics description of this electronics.
	 *
	 * @return the electronics description of this electronics
	 */
	@AutoEscape
	public String getElectronicsDescription();

	/**
	 * Sets the electronics description of this electronics.
	 *
	 * @param electronicsDescription the electronics description of this electronics
	 */
	public void setElectronicsDescription(String electronicsDescription);

}