/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package test.es.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ElectroType service. Represents a row in the &quot;ES_ElectroType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>test.es.data.model.impl.ElectroTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>test.es.data.model.impl.ElectroTypeImpl</code>.
 * </p>
 *
 * @author Andrey Pletenev
 * @see ElectroType
 * @generated
 */
@ProviderType
public interface ElectroTypeModel
	extends BaseModel<ElectroType>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a electro type model instance should use the {@link ElectroType} interface instead.
	 */

	/**
	 * Returns the primary key of this electro type.
	 *
	 * @return the primary key of this electro type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this electro type.
	 *
	 * @param primaryKey the primary key of this electro type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this electro type.
	 *
	 * @return the mvcc version of this electro type
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this electro type.
	 *
	 * @param mvccVersion the mvcc version of this electro type
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this electro type.
	 *
	 * @return the uuid of this electro type
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this electro type.
	 *
	 * @param uuid the uuid of this electro type
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the electro type ID of this electro type.
	 *
	 * @return the electro type ID of this electro type
	 */
	public long getElectroTypeId();

	/**
	 * Sets the electro type ID of this electro type.
	 *
	 * @param electroTypeId the electro type ID of this electro type
	 */
	public void setElectroTypeId(long electroTypeId);

	/**
	 * Returns the group ID of this electro type.
	 *
	 * @return the group ID of this electro type
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this electro type.
	 *
	 * @param groupId the group ID of this electro type
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this electro type.
	 *
	 * @return the company ID of this electro type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this electro type.
	 *
	 * @param companyId the company ID of this electro type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this electro type.
	 *
	 * @return the user ID of this electro type
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this electro type.
	 *
	 * @param userId the user ID of this electro type
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this electro type.
	 *
	 * @return the user uuid of this electro type
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this electro type.
	 *
	 * @param userUuid the user uuid of this electro type
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this electro type.
	 *
	 * @return the user name of this electro type
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this electro type.
	 *
	 * @param userName the user name of this electro type
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this electro type.
	 *
	 * @return the create date of this electro type
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this electro type.
	 *
	 * @param createDate the create date of this electro type
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this electro type.
	 *
	 * @return the modified date of this electro type
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this electro type.
	 *
	 * @param modifiedDate the modified date of this electro type
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the electro type name of this electro type.
	 *
	 * @return the electro type name of this electro type
	 */
	@AutoEscape
	public String getElectroTypeName();

	/**
	 * Sets the electro type name of this electro type.
	 *
	 * @param electroTypeName the electro type name of this electro type
	 */
	public void setElectroTypeName(String electroTypeName);

}